# Generated by Django 4.1.1 on 2022-10-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_rename_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='desc',
            field=models.CharField(max_length=200),
        ),
    ]
