# Generated by Django 4.1.1 on 2022-10-12 15:30

from django.db import migrations, models
import restapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_rename_cycle_id_image_cycle_remove_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to=restapi.models.upload_to),
        ),
    ]
