# Generated by Django 4.1.1 on 2022-10-17 07:58

from django.db import migrations, models
import restapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0012_new_trending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='image_1',
            field=models.ImageField(null=True, upload_to=restapi.models.upload_to),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='image_2',
            field=models.ImageField(null=True, upload_to=restapi.models.upload_to),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='image_3',
            field=models.ImageField(null=True, upload_to=restapi.models.upload_to),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='image_4',
            field=models.ImageField(null=True, upload_to=restapi.models.upload_to),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='image_5',
            field=models.ImageField(null=True, upload_to=restapi.models.upload_to),
        ),
    ]
