# Generated by Django 4.1.1 on 2022-10-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0014_cycle_highest_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='state',
            field=models.IntegerField(default=-1),
        ),
    ]
