# Generated by Django 4.1.1 on 2022-10-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0017_rename_bids_bid_cycle_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oid',
            field=models.CharField(default='google-oauth2|116792205554870559102', max_length=60),
            preserve_default=False,
        ),
    ]
