# Generated by Django 4.1.1 on 2022-10-22 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0018_user_oid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('mobile', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bid',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.appuser'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.appuser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
