# Generated by Django 4.1.1 on 2022-10-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=60, verbose_name='cycleName')),
                ('basePrice', models.PositiveIntegerField(blank=True, default=0, verbose_name='basePrice')),
                ('owner', models.CharField(blank=True, max_length=60, verbose_name='owner')),
                ('bidDeadline', models.DateField(auto_now=True, verbose_name='deadline')),
                ('buyOutPrice', models.PositiveIntegerField(blank=True, default=0, verbose_name='buyOutPrice')),
                ('viewCount', models.PositiveIntegerField(blank=True, default=0, verbose_name='viewCount')),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
