# Generated by Django 4.1.1 on 2022-10-12 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_alter_cycle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('url', models.CharField(max_length=50)),
                ('cycle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.cycle')),
            ],
        ),
    ]
