# Generated by Django 4.1.1 on 2022-10-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_cycle_desc_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
