# Generated by Django 4.1.1 on 2022-10-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_alter_cycle_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='cycle_id',
            new_name='cycle',
        ),
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='url', upload_to='media'),
            preserve_default=False,
        ),
    ]
