# Generated by Django 4.1.1 on 2022-10-17 07:06

from django.db import migrations, models
import restapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_remove_image_image_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=restapi.models.upload_to, verbose_name='cycleImage'),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to=restapi.models.upload_to, verbose_name='cycleImage'),
        ),
    ]
