# Generated by Django 4.1.1 on 2022-10-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0011_cycle_image_1_cycle_image_2_cycle_image_3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('cycle_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('cycle_id', models.IntegerField(null=True)),
            ],
        ),
    ]
