# Generated by Django 4.1.1 on 2022-10-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0013_alter_cycle_image_1_alter_cycle_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='highest_bid',
            field=models.IntegerField(null=True),
        ),
    ]
