# Generated by Django 4.1.1 on 2022-10-19 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0015_cycle_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('mobile', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('bid_price', models.IntegerField()),
                ('cycle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.cycle')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.user')),
            ],
        ),
    ]
