# Generated by Django 4.1.1 on 2022-10-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0019_appuser_alter_bid_user_id_alter_cycle_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='bidDeadline',
            field=models.DateTimeField(auto_now=True, verbose_name='deadline'),
        ),
    ]
