# Generated by Django 4.1.2 on 2022-11-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0021_alter_cycle_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='buyer',
            field=models.IntegerField(null=True, verbose_name='Buyer Id'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='bidDeadline',
            field=models.DateTimeField(verbose_name='deadline'),
        ),
    ]
