# Generated by Django 4.1.2 on 2022-11-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0022_cycle_buyer_alter_cycle_biddeadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='buyer',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
