# Generated by Django 4.1.2 on 2022-11-19 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0023_alter_cycle_buyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycle',
            old_name='user_id',
            new_name='user',
        ),
    ]
