# Generated by Django 4.1.2 on 2022-11-19 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0024_rename_user_id_cycle_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='cycle_id',
            new_name='cycle',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='user_id',
            new_name='user',
        ),
    ]
