# Generated by Django 4.1.2 on 2022-11-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0025_rename_cycle_id_bid_cycle_rename_user_id_bid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='uuid',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
