# Generated by Django 4.1.2 on 2022-11-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0026_cycle_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='purchased_amount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
