# Generated by Django 4.1.2 on 2022-11-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0029_remove_cycle_bidstart_cycle_bidstarttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='bidStartTime',
            field=models.DateTimeField(null=True),
        ),
    ]
